name: RuboCop linting

on:
  push:
    paths:
      - "Gemfile"
      - ".rubocop.yml"
      - ".github/workflows/rubucop.yml"
      - "**/*.rb"
  pull_request:
    paths:
      - "Gemfile"
      - ".rubocop.yml"
      - ".github/workflows/rubucop.yml"
      - "**/*.rb"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Rubocop
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rubocop -D -S
